name: CI

on:
  push:
    branches: [master]
    paths:
  pull_request:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/setup-action@v1
        with:
          install-lib: false
      - run: npm i
      - run: tree-sitter generate
      - uses: tree-sitter/parser-test-action@v1.2
        with:
          test-library: true
      - name: Parse Petalisp
        run: |
          git submodule init
          git submodule update
          if (( $(node_modules/tree-sitter-cli/tree-sitter parse test/Petalisp/**/*.lisp -q | wc -l) > 2 )); then # There are 2 known failures (strings that are not format strings but use ~X syntax)
            exit 1 
          else
            echo "Successfully parsed Petalisp."
          fi
          if (( $(node_modules/tree-sitter-cli/tree-sitter parse test/sly/**/*.lisp -q | wc -l) > 4 )); then # There are 2 known failures (strings that are not format strings but use ~X syntax)
            exit 1 
          else
            echo "Successfully parsed Sly"
          fi
